---
title: "Francisco_Group_Proj"
author: "Taylor Francisco"
date: "2023-11-26"
output: pdf_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r}
rm(list=ls())
```

#Set Up

##Load Packages

```{r}
library(tidyverse)
library(dplyr)
library(purrr)
library(readstata13)
library(plyr)
library(stargazer)
library(stringr)
library(ggplot2)
library(psych)
library(plm)
library(visreg)
library(VGAM)
library(car)
```

##Upload Data

```{r}
vote_df <- read_csv("Turnout_1980_2022_v1.0.csv")
abortion_policy_df <- read_csv("Abortion_Policies.csv") #this is an excel sheet I created based on raw file, clean data section will have code to allow for the replication of this excel sheet from the raw data
#raw abortion policy df
raw_abortion_df <- read_csv("raw_data.csv")
```

#Clean Data

##Voting dataset

```{r}
#check that there are only 50 states
unique(vote_df$STATE) #note District of Columbia included. also Pennsylvania* has a * added?

#get rid of US as a state- doesn't contain any information just a header interspersed with the data
vote_df <- vote_df %>% filter(STATE != "United States")
vote_df <- vote_df %>% filter(STATE_ABV != "DC")
unique(vote_df$STATE_ABV) #no more cleaning here, only 50 states

#change VEP_TURNOUT_RATE to be numberical, right now has % which makes it character
vote_df$VEP_TURNOUT_RATE <- as.numeric(sub("%", "", vote_df$VEP_TURNOUT_RATE))
class(vote_df$VEP_TURNOUT_RATE) #is now numeric
```

##Abortion Policy dataset

```{r}
#change column name to title for ease of coding
raw_abortion_df$title <- raw_abortion_df$`Title: Abortion Policy Tracker | KFF` 
#select only the string before the comma to leave just state title
raw_abortion_df <- raw_abortion_df %>%
    mutate(state=str_extract(raw_abortion_df$title, "^[^,]*")) %>%
    select(state)
#remove first three rows that are not states 
raw_abortion_df <- raw_abortion_df[-c(1, 2, 3), ]

#remove last rows that are also not states
raw_abortion_df <- raw_abortion_df[-c(52:nrow(raw_abortion_df)), ]

#get rid of DC
raw_abortion_df <- raw_abortion_df %>% filter(state != "District of Columbia")
#only 50 observations as wanted

#append restrictive level as a new row listed alphabetically
raw_abortion_df <- raw_abortion_df %>% mutate(Status_of_Abortion = c(4, 1, 2, 4,
                                                                     1, 1, 1, 1,
                                                                      2, 3, 1, 
                                                                     4, 1, 4, 2,
                                                                     2, 4, 4, 1,
                                                                     1, 1, 1, 1,
                                                                     4, 4, 1, 3, 
                                                                     1, 1, 1, 1,
                                                                     1, 3, 4, 2,
                                                                     4, 1, 1, 1,
                                                                     3, 4, 4, 4,
                                                                     2, 1, 1, 1,
                                                                     4, 2, 1))
#append binary changed variable as a new row listed alphabetically
raw_abortion_df <- raw_abortion_df %>% mutate(Changed = c(1, 0, 0, 1, 0, 0,
                                                          0, 0, 1, 1, 0, 1, 0,
                                                          1, 0, 0, 1, 1, 0, 0,
                                                          0, 0, 0, 1, 1, 0, 1,
                                                          0, 0, 0, 0, 0, 1, 1,
                                                          0, 1, 0, 0, 0, 1, 1,
                                                          1, 1, 1, 0, 0, 0, 1,
                                                          1, 0))
#append binary state law variable as a new row listed alphabetically
list(abortion_policy_df$`State Law`)
raw_abortion_df <- raw_abortion_df %>% mutate(State_Law= c(0, 0, 0, 0,
                                                          1, 1, 1, 1, 1, 0, 1, 
                                                          0, 1, 0, 1, 1, 0, 0,
                                                          1, 1, 1, 1, 1, 0, 0,
                                                          1, 0, 0, 1, 1, 0, 1,
                                                          0, 0, 0, 0, 1, 0, 1,
                                                          0, 0, 0, 0, 0, 1, 1, 
                                                          1, 0, 0, 0))
abortion_policy_df <- raw_abortion_df

#change state to STATE to allow for merging by state later on
abortion_policy_df <- abortion_policy_df %>% mutate(STATE = state)
#need to add STATE_ABV to merge with other two datasets
state <- read_csv("states.csv") #dataframe with just State name and State abbreviation
#change State to STATE to allow for merging by state later on
state <- state %>% mutate(STATE = State)

abortion_policy_df <- left_join(abortion_policy_df, state, by = "STATE")

#rename abbreviation to match other datasets 
abortion_policy_df <- abortion_policy_df %>% mutate(STATE_ABV = Abbreviation)
#since the mutate function keeps old state columns, get rid of for simplicity
abortion_policy_df <- abortion_policy_df %>% select("Status_of_Abortion",
                                                    "Changed","State_Law",
                                                    "STATE", "STATE_ABV")
```

##Combine dataframes for analysis

```{r}

#need just a dataframe of voting and state policy for DiD analysis (anes does not contain 2022)
vote_abort_df <- left_join(vote_df, abortion_policy_df, by = c("STATE_ABV"))

#save as csv to send to other group members cleaned data 
#write.csv(vote_abort_df, file ="vote_abort.csv", row.names = FALSE)
```

#Analysis

##Differences-in-differences delete presidential years from this analysis

```{r}
#remove Presidential election years 
# List of election years from 1980 to now
election_years <- c(1980, 1984, 1988, 1992, 1996, 2000, 2004, 2008, 2012, 2016, 2020)

# Remove rows corresponding to election years
vote_abort_df<- vote_abort_df %>%
  filter(!YEAR %in% election_years)


#create a variable with the year of "treatment" which is 2022
vote_abort_df$time = ifelse(vote_abort_df$YEAR >= 2022, 1, 0)
unique(vote_abort_df$YEAR)
unique(vote_abort_df$time)

#create interaction between time and the treated variable= changed 
vote_abort_df$did = vote_abort_df$time * vote_abort_df$Changed

#Estimating the DID estimator
didreg = lm(VEP_TURNOUT_RATE ~ Changed + time + did, data = vote_abort_df)
summary(didreg)

```

#Model with just a few election cycles before dobbs

```{r}
short_abort_df <- vote_abort_df %>% filter(YEAR >= 2009) 
#create a variable with the year of "treatment" which is 2022
short_abort_df$time = ifelse(short_abort_df$YEAR >= 2022, 1, 0)
unique(short_abort_df$YEAR)
unique(short_abort_df$time)

#create interaction between time and the treated variable= changed 
short_abort_df$did = short_abort_df$time * short_abort_df$Changed

#Estimating the DID estimator
didreg1 = lm(VEP_TURNOUT_RATE ~ Changed + time + did, data = short_abort_df)
summary(didreg1)

```

#DiD viz

```{r}
#code from https://lfoswald.github.io/2021-spring-stats2/materials/session-8/08-online-tutorial/
short_abort_df %>%
mutate(Changed = ifelse(Changed == 1, "Law Changed", "Law Remained the Same")) %>% 
mutate(time = ifelse(
      time == 0, "Pre-Dobbs (2010-2018)", "Post-Dobbs (2022)"
    )) %>%   
group_by(time, Changed) %>%  # group to extract means of each group at each time
dplyr::mutate(group_mean = mean(VEP_TURNOUT_RATE, na.rm=TRUE)) %>%  # extract means of each group at each time
ggplot(., aes(x = VEP_TURNOUT_RATE, fill = factor(Changed))) +
  geom_density(alpha = 0.5) +
  scale_fill_manual(name = " ", # changes to fill dimension
                     values = c("#cc0055", "#a7a8aa"),
                     labels = c("Treatment", "Control")) +
  facet_grid(Changed~factor(time, levels=c("Pre-Dobbs (2010-2018)", "Post-Dobbs (2022)"))) + # we specify the matrix (treatment and period)
  geom_vline(aes(xintercept = group_mean), linetype = "longdash") + # add vertical line with the mean
  theme_bw() +
  theme(legend.position = "none") +
  labs(x = "VEP Turnout Rate",
       y = "Density") +
  ggtitle("Voting-Eligible Population (VEP) Turnout Rate Pre- and Post-Dobbs") 


#change before times to be just one cycle before to make the two sides more comparable 
#add mean lines 
```


#adding in abortion restrictiveness

```{r}

short_abort_df$abort.fact <- factor(short_abort_df$Status_of_Abortion, levels = c(1, 2, 3, 4), 
                        labels = c("Abortion Legal", "Gestational Limit Between 15 and 22 LMP",
                                   "Gestational Limit Between 6 and 12 LMP", 
                                   "Abortion Banned"), exclude = NA, ordered= FALSE)
#change order so abortion banned is the default ref level for interpretation


didregabort = lm(VEP_TURNOUT_RATE ~ Changed + time + did + relevel(abort.fact, ref= "Abortion Banned"), data = short_abort_df)
summary(didregabort)

```

#try linear regression with just state law status

```{r}
latest_vote_abort_df <-short_abort_df %>% filter(YEAR==2022)

m5 <- lm(VEP_TURNOUT_RATE ~ relevel(abort.fact, ref = "Abortion Banned"), data =latest_vote_abort_df)
summary(m5)

```

```{r}
library(sjPlot)
library(sjmisc)
library(sjlabelled)

table <- tab_model(didreg, didreg1, didregabort, m5, auto.label = FALSE, collapse.ci = TRUE, 
                   pred.labels = c("Intercept", "Law Changed", "Time", "DiD", "Abortion Legal", "Gestational Limit Between 15 and 22 LMP",  "Gestational Limit Between 6 and 12 LMP"),
                  dv.labels = c("1982-2022 DiD", "2010-2022 DiD", "2010-2022 DiD with Levels of Restriction", "Linear Regression"))
table


```



